### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by danie21** [cornips/flobro#39]
can't move it. also, only launches from Google Chrome Store

**Comment by cornips** [comment]
You can move the windows by dragging the title bar. It appears when your mouse is at the top of the window (the bar is always visible in the settings page).

A shortcut to Flobro is available in Start Menu (Windows) or Spotlight (Mac), search for Flobro. I don't know how this is done in other OS's. Also, I don't know how long Google supports this for non Chrome OS systems, because Google is deprecating app support. Therefor issue #6 is planned for a future release.

**Comment by danie21** [comment]
Lol, I know how to move a window :| *jawdrop*. I obviously meant that the app wouldn't launch unless I launch it from the chrome store. Additionally, once it's running the window position is somehow locked. I've been using Flobro for months now and yesterday I noticed this problem. So maybe the last update had some things that weren't working across browsers, just saying
