### ISSUE TITLE
audio and video capture permission

### ISSUE THREAD

**Issue by deepakkoirala** [cornips/flobro#43]
I was using this plugin wisely from a long time. Suddenly  after July 20, I was asked by chrome to enable camera and audio permission to continue using this extension. This ended up removing the plugin. Giving Audio and Camera permission doesn't make sense.

**Comment by cornips** [comment]
This had to do with #13. In order to support websites using these features, Flobro needed permission for the whole app. The app itself NEVER uses video or audio.

Because the permission is unclear and raised many questions, it will be removed in the upcoming release. Future support for websites using webcam and audio will be handled in the original issue #13.
