### ISSUE TITLE
Flobro doesn't have access to audio devices

### ISSUE THREAD

**Issue by Bukowskaii** [cornips/flobro#62]
**Describe the bug**
Opening any website that requests access to microphone/audio devices doesn't allow access to those devices. In my case, discordapp.com

**Steps to reproduce**
Open FloBro
Set url to discordapp.com
Login -> Select Settings -> Voice & Video
Input and Output devices only show "Default" and I can't specify which device to use. Additionally, it doesn't detect my microphone at all. 

**Expected behavior**
I would expect a popup to access my audio devices like in chrome to appear in order to select and use different audio and video devices

**Screenshots**
![image](https://user-images.githubusercontent.com/4584035/79624430-67bcbb00-80d6-11ea-907c-422703da6c42.png)
![image](https://user-images.githubusercontent.com/4584035/79624435-6db29c00-80d6-11ea-8804-ba041c3948db.png)
https://support.discordapp.com/hc/en-us/articles/205093487

**Environment variables:**
Windows 10
Chrome 81.0.4044.113

**Comment by wayno2020** [comment]
+1. I would imagine this is one of the primary use cases, if not **the** primary use case.

**Comment by cornips** [comment]
This feature was requested in issue #13 but caused privacy issues because Flobro needed webcam and microphone access, and many users uninstalled the app as a result. It is not possible for a Chrome App to ask for permissions per website, it has to be a global permission. Therefor the feature was removed.
I hope to return this feature on a per website base when Flobro is an independent application.
