### ISSUE TITLE
title bar is bouncing the window

### ISSUE THREAD

**Issue by S1lverone** [cornips/flobro#72]
please make the titlebar just stay. it keeps boucing the window every time I enter or leave the window

**Comment by cornips** [comment]
Pinned titlebar was [removed in 0.2.4](https://github.com/flobro/flobro-chrome-app/releases/tag/0.2.4).
The titlebar now appears everytime you 'mouseover' the window, as you already found out.
The pin option was unclear. People expected it to toggle the stay-on-top option, so the pin now controls the stay-on-top option. This issue is related to #71 

If you find the 'bounce' effect annoying, you can turn off the "Fit webview when title bar appears" option in settings. Then the titlebar would overlap instead of resize the webview.

**Comment by S1lverone** [comment]
Amazing. It sorted it out. Thx.
Do you plan on adding a forward og backwards function.  I case i click on a
link or search on google?

tor. 3. sep. 2020 02.53 skrev Martijn Cornips <notifications@github.com>:

**Comment by cornips** [comment]
I just added issue #79 for adding backwards/forwards buttons

**Comment by S1lverone** [comment]
Cool thx

tir. 15. sep. 2020 01.45 skrev Martijn Cornips <notifications@github.com>:

**Comment by tanveerapple** [comment]
I believe one of the purpose at least my only purpose was to hide the top bar when you are working inside to show/demo. If the top bar keeps up showing, we can just use the google chrome itself to adjust the size, isnt it?
Can you please enhance your product so that, the flobro top bar does not show at all, and just shows when you imitate/open the app?
