### ISSUE TITLE
Title bar pop up and mouse drag issues

### ISSUE THREAD

**Issue by alia-peterson** [cornips/flobro#74]
**Describe the bug**
Typically the title bar only pops up when the mouse is entering or exiting the window but now it's popping up every time I move my mouse which makes the top 1/2" or so of my screen unusable. 
Also, every time i click my mouse the app acts as if I'm holding down the left button and tries to drag whatever i clicked on. 

**Steps to reproduce**
1. Move mouse
2. Click on anything

**Expected behavior**
I expect that the title bar will stay minimized while i'm working within the screen and that the mouse click will respond correctly.

**Environment variables:**
 - OS: Mac 
 - Version: Catalina 10.15.6
 - Chrome version: 85.0.4183.83

**Comment by cornips** [comment]
Related to #73.
I think a better solution would be a toggle for the toolbar without any mouse-over action whatsoever.

For now, if you're looking for a way to stop the toolbar from 'popping' up, you can turn off the "Fit webview when title bar appears" option in settings. Then the toolbar would overlap instead of resize the webview.
This isn't a solution for your issue but maybe it helps a bit. Same as for #72.

**Comment by cornips** [comment]
Fixed in 7d200b2
